### ISSUE TITLE
Review graph exploration tools

### ISSUE THREAD

**Issue by jacobdanovitch** [amandaLi7/HTUI#8]
* [x] i2
* [x] Maltego
* [ ] Argo
* [x] Confirm that none of the existing tools are interactive

**Comment by nair-p** [comment]
Included a more detailed account of visualization tools used by law enforcement on the overleaf document. The main point in which our tool differs is in the fact that it can accommodate algorithms that learn from the data/user rather than simply highlight the hard links in the data connecting entities.
